packages:
  - name: codename
    actions:
      - name: generator
        runtime: 'python:default'
        limits:
          memory: 384
      - name: mrta_generator
        runtime: 'python:default'
        limits:
          memory: 384
      - name: bts_generator
        runtime: 'python:default'
        limits:
          memory: 384